version: '3'

services:
 proxy:
  build:
      context:  ./proxy
      dockerfile: Dockerfile
  ports:
    - 8080:8080
    - 8081:8081
  restart: always
 
 nginx:
  depends_on:
   - proxy
  image: nginx:alpine
  restart: always
 
 apache:
  depends_on:
   - proxy
  image: httpd:alpine
  restart: always
